version: '3.8'

services:
  # --- BASE DE DATOS COMPARTIDA (PostgreSQL) ---
  postgres-db:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin_user
      - POSTGRES_PASSWORD=admin_pass
      - POSTGRES_DB=postgres # DB por defecto
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # Script para crear las DBs de mlflow y airflow al inicio
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ml-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- ZOOKEEPER & KAFKA (Ingesta) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - ml-net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ml-net

  # --- STACK DATA SCIENCE (Spark + Jupyter + MLflow) ---
  stack-completo:
    build: .
    container_name: python_ml_stack
    ports:
      - "8888:8888"  # JupyterLab
      - "8080:8080"  # Spark Master UI
      - "5000:5000"  # MLflow UI
      - "7077:7077"  # Spark Master Port
    volumes:
      - ./notebooks:/app/notebooks
      - mlflow-artifacts:/app/mlflow_artifacts
    networks:
      - ml-net
    environment:
      - SPARK_MASTER=spark://localhost:7077
      # Apuntar a la base de datos creada en init.sql
      - BACKEND_STORE_URI=postgresql://admin_user:admin_pass@postgres_db:5432/mlflow_db
      - JUPYTER_TOKEN=hola-mundo
    depends_on:
      postgres-db:
        condition: service_healthy
      kafka:
        condition: service_started

  # --- AIRFLOW (Orquestaci√≥n) ---
  airflow-init:
    image: apache/airflow:2.7.1
    container_name: airflow_init
    command: version
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin_user:admin_pass@postgres_db/airflow_db
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - _AIRFLOW_DB_UPGRADE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    networks:
      - ml-net
    depends_on:
      postgres-db:
        condition: service_healthy

  airflow-webserver:
    image: apache/airflow:2.7.1
    container_name: airflow_webserver
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin_user:admin_pass@postgres_db/airflow_db
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    ports:
      - "8081:8080" # Mapeado a 8081 para no chocar con Spark
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - ml-net
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.1
    container_name: airflow_scheduler
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://admin_user:admin_pass@postgres_db/airflow_db
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
    volumes:
      - ./dags:/opt/airflow/dags
    networks:
      - ml-net
    command: scheduler

volumes:
  postgres-data:
  mlflow-artifacts:

networks:
  ml-net:
    driver: bridge